### ISSUE TITLE
Please review the design of Preview 2 bounty program, let me know if you can understand it, and how to improve

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#40]
https://github.com/tearust/moderators/blob/main/Preview%20release%20plan/Preview2%20Bounty.md

We can discuss this idea. Do you think it will work? 
how can we market this bounty so that many community tester can join the mining

**Comment by geopor** [comment]
I like that the awards are given out proportionally to the top 10, that allows more people to compete and we can see a few different winning strategies.

It might be confusing for some miners as they think they are competing in a mining contest and they get overtaken on the leaderboard by people who invested in blog posts and tweets. 

It's very complex because the best competitors will maximize their Camellia through mining or selling seeds, and should only stake T if they aren't confident enough to pick winning ProjectTokens. There will be a limit on how well miners will do if they only want to mine and not participate in any of the bonding curves.

I like the dApp example, it shows how good code on the platform can generate investment and then return it as a dividend through the bonding curve. It also makes sense that dApps on the TEA platform will create their own ProjectTokens and become another point of participation / investment for T token holders.

I'm a little less certain about the contests. In the example, the writer has a following specifically of other users who have T tokens to purchase his token on the bonding curve. It seems like this is not likely, and is only a possibility in the future when the TEA Project develops influencers who evangelize for the TEA platform. The influencers not only have to encourage their followers to participate in a bonding curve but to also exchange their DAI etc for the T token. I understand how dApps use the bonding curve, but outside of the TEA Project giving out rewards for blog posts / tweets etc I'm not sure I understand the value proposition of someone outside the platform using it as a crypto version of Kickstarter.

**Comment by kevingzhang** [comment]
> It might be confusing for some miners as they think they are competing in a mining contest and they get overtaken on the leaderboard by people who invested in blog posts and tweets.

We do not need to call it a mining contest. Or, we can clarify and extend the definition of mining. Making money from our project is called mining, doesn't matter plant a CML or not. 
Or we can change the word "mining" to "farming". what do you think?

> It's very complex because the best competitors will maximize their Camellia through mining or selling seeds, and should only stake T if they aren't confident enough to pick winning ProjectTokens. There will be a limit on how well miners will do if they only want to mine and not participate in any of the bonding curves.

This is exactly what we can to test the business model. We do not know whether mining can make more money or simply investment can make more. Right now in the capilized United States, investment can obviously make more money than doing real work. I am not sure if it applied to TEA ecosystem as well.

> I'm a little less certain about the contests. In the example, the writer has a following specifically of other users who have T tokens to purchase his token on the bonding curve. It seems like this is not likely, and is only a possibility in the future when the TEA Project develops influencers who evangelize for the TEA platform. The influencers not only have to encourage their followers to participate in a bonding curve but to also exchange their DAI etc for the T token. I understand how dApps use the bonding curve, but outside of the TEA Project giving out rewards for blog posts / tweets etc I'm not sure I understand the value proposition of someone outside the platform using it as a crypto version of Kickstarter.

Actually, I do not know the result either. That's the purpose of the business model trial. Of course, we are open to other business models that we can try. Looking for those kind of influencer and give them reward is exactly what we are trying to do. Except for this idea, I do not have other solution where and how to find those influencers yet. Giving reward to those influencer is much better than simply air drop free money to all community members. 
during the preview stage, there will not be the bridge between TEA and ETH. The only way to make T is through mining or exchange with others who owns T.

**Comment by kevingzhang** [comment]
@waaghree and @lxm218 welcome to the discussion as well.

**Comment by geopor** [comment]
I understand now the competitions are a form of targeted marketing, that can be good for the project.

I think if the contest to reach the top 10 of the leader board, we can just emphasize that they have many methods to reach the goal: mining as well as investing in dApps / one-off ProjectTokens. Allowing contestants multiple ways to reach the top of the leaderboard seems like a great way to introduce them to the platform.

**Comment by kevingzhang** [comment]
yes, but the development of all features takes time. The investment to dApp will be added in later epoch. so we can only start with basic mining / staking features

**Comment by geopor** [comment]
Ok emphasis on mining and staking is much more straightforward. Marketing will be grassroots primarily through Telegram and Reddit encompassing potential miners and crypto enthusiasts worldwide.
