### ISSUE TITLE
UI issue for wallet - retracting bids

### ISSUE THREAD

**Issue by geopor** [tearust/moderators#47]
<img width="1107" alt="Auction - My Bid List - cant delete bid" src="https://user-images.githubusercontent.com/86096370/126693366-47eb2bde-9ac3-42ba-8a3b-9bbcbab23f42.png">

This is the dialogue after clicking the garbage button (currently doesn't have a tooltip popup).

• Text should read:
You can't delete this bid until someone bids higher.

@kevingzhang How useful is this function? If you must wait for someone to bid higher to retract your bid it wouldn't matter because you won't win the auction anyway.

**Comment by kevingzhang** [comment]
If you are currently at the highest position in the auction, you are the winner. You are not allowed to delete (or withdraw) since you are cheating the system and other competitors. If you are the highest, you are the winner, you are the one who should take the seed if no one else takes over the highest position.

Did I make it clear?

**Comment by geopor** [comment]
I'm trying to imagine a scenario where this 'withdraw' button is useful given those rules and can't think of any.

- If sudo is the high bidder and wants to withdraw from the auction he can't, those are the rules, so the button isn't useful in this scenario.
- sudo has to wait for another higher bidder before he can withdraw his bid. 
- Let's say elon bids 117 T. Now sudo can withdraw his bid with this button but why should he bother? Basically, elon is stuck as he has to wait for someone to bid higher than him so that he can use the withdraw button himself to retract his bid. 
- If satoshi bids 118 T, then both sudo and elon can use the 'withdraw' button but why would they bother? They know satoshi is stuck as the high bidder and don't have to worry about their bids being accepted.

**Comment by kevingzhang** [comment]
let me explain. 
1. If there is no withdraw or retract button, sudo will not win the bid but he cannot withdraw his deposit until the next trade window. If sudo would like to give up this bid since Elon has higher bid, it would better for him to retract/ withdraw, since his deposit will be back. He can use his money to bid on something else.  If no such a button, his deposit will be locked until this round is over.
2. If we do not have such a limitation. Someone can fool the system by put a super high bid that defeat all other competitors, but at the last second, he withdraw his bid, then this auction will be either fail or fall to someone with much lower bid. This is unfair.

**Comment by geopor** [comment]
Ok I didn't realize bidding locked up funds.
