### ISSUE TITLE
turn "The logic behind our Go2Market strategy" into a video scripts

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#52]
We need the 2nd batch of our video explainer series.
This is one of them.
I write the idea at https://github.com/tearust/moderators/blob/main/Go_to_market_plan/The%20logic%20behind%20our%20Go2Market%20strategy.md

Please understand the idea, rewrite into a video scripts. we will use the same video maker to build this video.

**Comment by kevingzhang** [comment]
This video should have a link to the previous "What is TEA Project" at the beginning. by saying "For detail about what TEA project is, please click the top right corner..."

**Comment by kevingzhang** [comment]
this may change our current pitch deck on the last 2nd page, the team and milestones. We probably need to update that page to fit the go2market strategy

**Comment by geopor** [comment]
Updated pitch deck, will need to be uploaded to /pdf directory:

![Pitch Deck - The TEA Project](https://user-images.githubusercontent.com/86096370/127923976-40cea59c-b15d-45da-961b-15ef8c1c084d.png)

**Comment by geopor** [comment]
[Pitch_deck.pdf](https://github.com/tearust/moderators/files/6919638/Pitch_deck.pdf)

**Comment by geopor** [comment]
If you're new to the TEA Project and want to learn more, please click the link in the top right corner of the video.

The TEA Project features a rich, evolving ecosystem where developers, miners, and consumers all create demand for the TEA token. Consumers need the TEA token to pay for services or consume the content from TApps. The consumer usage of TApps indirectly helps create demand for the TEA token. But you might be wondering why developers would choose the TEA Project as their development platform and build TApps?

From a technical perspective, the TEA Project allows developers and their apps a simplified bridge to the decentralized era. Most existing cloud computing technologies can be used in TApps development. Developers can continue using their favorite programming languages to compile their programs into the Web Assembly format. The TEA Project's hardware and software-agnostic design greatly reduces any barriers to entry.

For fundraising, the TAppStore provides bonding curves to turn future app revenue into early investment support. These investors are mostly TEA miners and consumers such as TApp curators. This makes the TAppStore not only an app store, but also a community to connect developers, miners, and consumers.

Miners will likely make up the majority of the early TApp investors because they have TEA to invest from TEA farming. A carefully designed mining economy is the key factor for incentivizing miners to invest their earnings. The TEA Project's staking program is designed to encourage early miners to continually reinvest their harvests. The built-in incentives to either stake TEA or use it to buy more Camellia helps maintain the scarcity of both the TEA token and Camellia token. This, in turn, reduces the sell-off pressure and keeps the token price stable. If the token price rises, miners will be glad to see their reinvestment strategy positively supporting the TEA token price. This becomes the core of the TEA miners' token economy.

Ok, now that we've explained the design philosophy behind the TEA Project's tokenomics, let's take a more in-depth look at how the early-stage participants of the TEA Project, miners, developers, and consumers, all help support the TEA token's price stability by playing off each other's actions.

In phase one of the TEA Project, we focus on the miners' economy. We'll start with a TEA farming competition to help prove that our miner tokenomics is sound. Once we get evidence that the miners' tokenomics works, we'll begin the real-life mainnet so that miners can accumulate crypto assets. In this phase, miners can reinvest their harvested TEA tokens back into staking or purchasing more Camellia. These staking opportunities won't last forever. And when the best staking slots have all been occupied, the miners might have more TEA than they have places to invest it. That's when we need to our phase 2 as quickly as possible so that miners can start investing in TApps.

In phase two, we move our focus to app developers. The TAppStore is the core of phase two. It allows miners who've harvested large amounts of TEA tokens to extend their investments into app development. Each TApp's bonding curve is where miners can put their TEA tokens to invest in future killer apps. An inherent feature of bonding curves is that early investors get the best ROI, who are usually the developers themselves. They can turn future revenue into an immediate funding pool to support development. This is a much better approach than the outdated ICO model. The TEA Core Team will first bring in a few demo TApps to showcase to developers and demonstrate how the bonding curve funding mechanism works.

The TApps won't generate revenue by themselves; consumers are eventually needed to support the token price. So now we move to phase three which focuses on the consumer. The TApp developers are incentivized to make useful apps that meet consumer demand. Only those tApps that satisfy consumers can gain investors and curators as well as consumer payments. As long as the TApps are useful, consumers will use them to consume their special content or service by paying TEA tokens into the bonding curve as a "consume action". In turn, their payment will be distributed to the TApp token holders, both investors and developers. The TApps round out the "consume action" by burning fuel and supporting the host miners.

Now you can see how all three phases reinforce each other. The resulting TApps will have a user interface similar in quality to existing cloud apps with one big benefit: they'll run decentralized on TEA Project's network. Imagine if only 1% of cloud-based web apps migrated to the TEA Project platform ... the market size of these migrated apps would be tremendous in size. And all the early TEA miners, developers, curators, and consumers would greatly benefit from it.

**Comment by kevingzhang** [comment]
looks good. do you think it is good enough to make a video?
