### ISSUE TITLE
write tokenomic video scripts based on medium blog

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#53]
https://github.com/tearust/moderators/blob/main/Go_to_market_plan/TEA%20miners%20tokenomic.md

**Comment by geopor** [comment]
The TEA Project's miners are primarily interested in being compensated for joining the network. If we use the analogy that the TEA Project is to cloud computing what Uber is to cars, you could say that the TEA Project needs to incentivize its miners the same way that Uber needs to incentivize car owners to drive. There's no centralized company to pay salaries or own the mining nodes, so a carefully designed token economy must keep the miners interested enough in the rewards to keep their hardware engaged with the network. The TEA Project's tokenomics plan helps keep the network running smoothly and creates enough speculation to boost growth.

More than the TEA project's underlying tech, what miners care most about is their ROI. Miners have just two questions:

- How many tokens can I mine given a particular investment of hardware, maintenance, and time?
- Will the token price increase or at least reasonably maintain its value?

Miners will be glad to know that TEA Project mining doesn't require beefy hardware. Compared to other crypto-mining projects, the TEA project is very **green**. It doesn't require powerful processors that consume lots of energy, and it doesn't have significant output demands that would require terabytes of hard drive space. A TEA mining machine can be a small, inexpensive IoT machine. The design of the system makes it so that hardware is affordable enough for most miners. The majority of the mining cost comes from the Camellia NFT.

Miners must purchase Camellia seeds through an open auction. When new Camellia seeds are generated and sold through bidding, the DAO burns the TEA paid by the bidder. Because the supply of seeds is heavily controlled and limited, the Camellia price will rise, as will the price of the TEA token since miners will need it to buy seeds. Miners want to purchase seeds because mining TEA is profitable, which is another feedback loop keeping upward pressure on the price of TEA.

The regular DAO burning of TEA adds supply shocks that also help the price of TEA. The Camellia seeds that miners receive in exchange for their burned TEA tokens need time to grow when planted into a mining machine. These early-stage mining machines have a relatively low harvest yield of TEA tokens as the miners wait for their planted Camellia to mature. 

We can start to see how the circulation of TEA tokens becomes an infinity loop:
- Miners buy more seeds to do more mining.
- The DAO then burns the TEA that miners have paid for seeds.
- Miners wait for their planted Camellia to mature and produce more TEA tokens that are useful for buying more seeds.

We want to watch this infinity loop work but it stills needs a way to get started. At the beginning of the TEA Project there's really nothing there yet to jumpstart the loop: there are no TEA tokens in the TEA blockchain, only frozen Camellia seeds. The defrost schedule of the Camellia seed NFTs is governed by an algorithm such that very few are defrosted at the beginning. These few lucky defrosted seeds belong to early investors, who will start mining by planting their defrosted Camellia. And now finally we have some TEA entering the TEA system as miners begin harvesting TEA at a relatively low outcome rate because the planted Camellia needs time to grow. The TEA supply is minimal at this point, and all the TEA owners are early investors. It's safe to assume that they know the value of TEA and Camellia. Otherwise, they wouldn't have invested in the TEA Project. Just as early real estate investors jump in to buy land surrounding a planned development region, these early investors are accumulating valuable assets at the early stage of the project. Since they know the TEA Project's value, they're not likely to dump the TEA on the open market. 

Instead, they're likely to invest their harvested TEA into staking slots of other miners' machines as well as buying more Camellia seeds to start more mining nodes. The incentive for them to invest their TEA is to occupy the best staking slot positions, which become scarcer over time. If most of the early TEA tokens are reinvested, there would be a limited supply in the market. No doubt the TEA price will go higher in that likely scenario, not to mention that the early investors likely have lots of money to buy more TEA tokens from the market.

Interestingly enough, if the TEA price jumps up, the more profitable it is for TEA farming as a business. If TEA farming is profitable, then more miners will likely want to jump into TEA farming, but they will need TEA to buy Camellia seeds. So the TEA price will benefit from more miners coming on board.

This all sounds good, but you might be wondering what would happen if TEA token holders started to dump their holdings. Now miners and early investors are generally OK with price fluctuations, but they don't want to see the token dump. A massive token dump for any cryptocurrency signals a loss of confidence in the project by its token holders. And while there's no way to prevent someone from trying to dump TEA on the open market, there are safeguards in place to prevent this from happening. 

Consider that in the early stages, the TEA harvests are minimal. There shouldn't be too much farmed TEA available to be sold on the market. This limited supply would make it much easier for market makers to buy and keep the price stable. As long as the price can stay at a healthy level and increase gradually, those who sold their TEA previously would regret their rash behavior. Therefore, the miners and long-term hodlers who believe in the project can easily absorb such dumps that would eventually appear as blips on the larger time frame.

Now of course building a new mining community is very difficult. The TEA project won't create such a new community from scratch. The key for onboarding new miners is leveraging existing mining communities by showing how the TEA project can bring them value. For example, IPFS miners can merge mine both the FIL and TEA tokens. TEA makes IPFS into "Interplanetary Function as a Service" rather than just a file system. TEA dApps need code and data storage on IPFS, which adds another real use case for IPFS. Other smart contract platforms such as Polkadot and Ethereum can offload their computing tasks to the TEA network. This offloading is not a diversion of their profit; it rather creates more rich computing demands that were originally not doable on their blockchains. In return, more dApps can run on their blockchain and generate more revenue. TEA is not trying to compete with or divert profit from other partners but to create new user demand that benefits all.

We should mention that no matter how well we design the miners' economy to initially boost the TEA token, it's still a short-term solution. In the long run, there needs to be usage demand for TEA tokens. The TEA project team has started working on the so-called Rich dApps that run on the TEA network. Leveraging the existing Filecoin, Polkadot, and Ethereum communities helps us look forward to their cooperation in building this larger ecosystem. One example is by adding computing modules to IPFS nodes; this enables IPFS miners to merge mine both FIL and TEA tokens. The dApps will also need to store data and code on IPFS, bringing more real use cases for IPFS. This is a win-win-win situation.
