### ISSUE TITLE
use this script for next video

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#54]
https://github.com/tearust/moderators/issues/52

**Comment by lxm218** [comment]
here is the video: https://drive.google.com/drive/u/0/folders/1BTKHZx584NlEqVyVPvh7Ejk1GWpVCJs3
please provide comments

**Comment by geopor** [comment]
## Requested edits

**:23** - _Tapps_ should read **TApps** in the graphic

**1:15** - T-Miners, the upper left image should use the miner graphic instead, this one:

<img width="600" alt="Screen Shot 2021-08-10 at 10 51 53 AM" src="https://user-images.githubusercontent.com/86096370/128912792-80134fd5-9c5e-4a39-897b-24411b694d4e.png">

**1:32** - Audio and visual both need edits here.
- Audio should say **TEA Mining** instead of _TEA Farming_, and the writing should match
- The visual image of the bar graph should be replaced with this image:
https://dribbble.com/shots/6368409-Digging-for-gold/attachments/6368409-Digging-for-gold?mode=media

**3:12** - Replace image of the existing miner person with the miner graphic mentioned above at 1:15

**5:08** - Lower right cloud apps image, replace with this image: http://clipart-library.com/newhp/405-4056966_clipart-clouds-cloud-computing-cloud-iot-png-download.png

**5:15** - The image at 5:08 should now transition to this image: https://i2.wp.com/blog.sunshower.io/wp-content/uploads/2019/05/aws-azure-google-1.png?w=501&ssl=1

**Comment by geopor** [comment]
Updated comment above for pronunciation of **TApps**

**Comment by lxm218** [comment]
revised version is here: https://we.tl/t-OxW8Iuk3GS?src=dnl
Please check, if you think it's good, please post it on youtube channel.

**Comment by geopor** [comment]
Uploaded: https://www.youtube.com/watch?v=WUV_SVMTgT0
