### ISSUE TITLE
Read the change on the preview 1 contest rule https://github.com/tearust/moderators/commit/68b36d1ed989f5040a78ec639b7658484021ebb4

### ISSUE THREAD

**Issue by kevingzhang** [tearust/moderators#65]
After our dev discussion, we have confirmed the rule of preview 1, esp how to evaluate the assets.
I make a change in the md file here https://github.com/tearust/moderators/commit/68b36d1ed989f5040a78ec639b7658484021ebb4

In this case, we will have a single way to calculate the assets. So we only need ONE contest instead of two. This makes our contest easier to explain.

The profitability is converted to one week profit value. This profit add to existing cash value so the evaluation can be calculated this way. 

Regarding should we have 10 winners. My suggest is a percentage instead of a fixed number. For example, round up of 5% of total candidates are winners. This can help the case that too few candidates. 

What do you think? please discuss in this issue

**Comment by geopor** [comment]
5% of total contestants is a good way to scale the rewards to the # of participants. Total cash value of assets will allow some testing of tokenomics, how much they will dump rewards vs reinvest, I think it looks good.

**Comment by kevingzhang** [comment]
1. We have the Genesis Exchange and Leader board already. Please see if they meet our requirements
2. There is a potential attack. The contestants can create a large number of fake or bot contestants. If those bots are 95% of the contestants, so every real human contestants will be winner. How to defeat this?

**Comment by geopor** [comment]
We can require them to join our Telegram group, have them introduce themselves. We can have them enter their Telegram ID into the signup form and we can check they are members of our group.

This is the existing signup form: https://docs.google.com/forms/d/e/1FAIpQLSdNyJVmRjyYImTtTJ3AEzk8y6s3ZfCnoxMEzfbyYi_vVdIIzg/viewform

**Comment by kevingzhang** [comment]
do you mean asking them to join telegram to prevent the attack?

**Comment by geopor** [comment]
We can either require it - drawback is it might exclude some people or lose some legit people who don't want the hassle, or we can incentivize Telegram signup. If Telegram signup to our group was optional - because we don't want to exclude any people who might not be active on Telegram - we can incentivize Telegram signups by giving these people who signup a higher chance of receiving A & B seeds, they just have to leave a message that they've read the readme and we can tell them to ask any questions they have. If that were the case, we would need only 5 honest people to negate 95 spammers because spammers won't have any strategy during the contest, just spam techniques, and if we incentivize Telegram signups with better seeds these Telegram people would be more likely to win. I don't think spammers will go through all of this, it does increase the cost of attack. So we just need 5 honest nodes out of every 100 signups to reach a fair contest :)

Also, it would help increase our Telegram numbers as it's not active right now.

**Comment by kevingzhang** [comment]
How about this? We tell them we will announce the important information (such as when to start) in those IM group. If you do not join the group, you might lose the advantage and be beaten by other front runners.

**Comment by geopor** [comment]
That is a good idea, anything requiring human interaction is good.

**Comment by kevingzhang** [comment]
Please do it in the landing page. and let me review when done. I hope to see it early this afternoon. If nothing wrong, I would like to release it to public today
I hope to get more registers as early as possible

**Comment by geopor** [comment]
Working landing page: https://a9008jngsou5.umso.co

Will export to host on our servers when it looks good / no more changes.

**Comment by kevingzhang** [comment]
good enough for now. we can deploy it when you are OK.

**Comment by geopor** [comment]
WeChat link they will have to get through Telegram, so it should be fine for now. Google Analytics also installed.

[landing-page-1-download.zip](https://github.com/tearust/moderators/files/6965072/landing-page-1-download.zip)

**Comment by liyangwood** [comment]
deployed
https://github.com/tearust/website/tree/main/frontend/landingpage/preview_1
Here is source code, just modify it directly.

**Comment by geopor** [comment]
Live at https://teaproject.org/landingpage/preview_1/
